url: https://mseew.github.io
baseurl: /portfolio/

# Site settings
title: Marie Whittaker
email: marieclaire.whittaker+design@gmail.com
description: "Marie Whittaker is a designer based in Washington, DC"

# Team names, titles and social links
people:
- name: Marie Whittaker
  pic: 1
  position:
  social:
    - title: twitter
      url: https://twitter.com/MarieCWhittaker
    - title: Github
      url: https://hithub.com/mseew
    - title: #
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/MarieCWhittaker
  - title: github
    url: http://github.com/mseew

# Postal address (add as many lines as necessary)
address:
  - line: Washington, DC 20011

# Build settings
markdown: kramdown
permalink: pretty